// Generated by gencpp from file my_first_service/AddTwointsSrv.msg
// DO NOT EDIT!


#ifndef MY_FIRST_SERVICE_MESSAGE_ADDTWOINTSSRV_H
#define MY_FIRST_SERVICE_MESSAGE_ADDTWOINTSSRV_H

#include <ros/service_traits.h>


#include <my_first_service/AddTwointsSrvRequest.h>
#include <my_first_service/AddTwointsSrvResponse.h>


namespace my_first_service
{

struct AddTwointsSrv
{

typedef AddTwointsSrvRequest Request;
typedef AddTwointsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwointsSrv
} // namespace my_first_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_first_service::AddTwointsSrv > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::my_first_service::AddTwointsSrv&) { return value(); }
};

template<>
struct DataType< ::my_first_service::AddTwointsSrv > {
  static const char* value()
  {
    return "my_first_service/AddTwointsSrv";
  }

  static const char* value(const ::my_first_service::AddTwointsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::my_first_service::AddTwointsSrvRequest> should match
// service_traits::MD5Sum< ::my_first_service::AddTwointsSrv >
template<>
struct MD5Sum< ::my_first_service::AddTwointsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_service::AddTwointsSrv >::value();
  }
  static const char* value(const ::my_first_service::AddTwointsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_service::AddTwointsSrvRequest> should match
// service_traits::DataType< ::my_first_service::AddTwointsSrv >
template<>
struct DataType< ::my_first_service::AddTwointsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::my_first_service::AddTwointsSrv >::value();
  }
  static const char* value(const ::my_first_service::AddTwointsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_first_service::AddTwointsSrvResponse> should match
// service_traits::MD5Sum< ::my_first_service::AddTwointsSrv >
template<>
struct MD5Sum< ::my_first_service::AddTwointsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_service::AddTwointsSrv >::value();
  }
  static const char* value(const ::my_first_service::AddTwointsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_service::AddTwointsSrvResponse> should match
// service_traits::DataType< ::my_first_service::AddTwointsSrv >
template<>
struct DataType< ::my_first_service::AddTwointsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::my_first_service::AddTwointsSrv >::value();
  }
  static const char* value(const ::my_first_service::AddTwointsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_FIRST_SERVICE_MESSAGE_ADDTWOINTSSRV_H
